import type { Point } from "./types";

export const samplePoints: Point[] = [
  {
    id: "1",
    name: "Iglesia El Buen Pastor",
    address: "210 Bloomfield Ave, Newark, NJ",
    city: "NJ",
    status: "abierto",
    mapsUrl: "https://maps.google.com/?q=210+Bloomfield+Ave+Newark+NJ",
    donationInfo: null,
    needs: [
      { id: "1-1", item: "Agua embotellada", priority: "alta" },
      { id: "1-2", item: "Pañales talla 3-4", priority: "alta" },
      { id: "1-3", item: "Linternas y pilas", priority: "media" },
    ],
    updatedLabel: "hace 12 min",
  },
  {
    id: "2",
    name: "Centro Comunitario Colombo-Americano",
    address: "85-15 37th Ave, Jackson Heights, NY",
    city: "NYC",
    status: "saturado",
    mapsUrl: "https://maps.google.com/?q=85-15+37th+Ave+Jackson+Heights+NY",
    donationInfo: null,
    needs: [{ id: "2-1", item: "Ropa de invierno", priority: "baja" }],
    updatedLabel: "hace 40 min",
  },
  {
    id: "3",
    name: "Restaurante La Fonda Paisa",
    address: "512 Bergenline Ave, Union City, NJ",
    city: "NJ",
    status: "abierto",
    mapsUrl: "https://maps.google.com/?q=512+Bergenline+Ave+Union+City+NJ",
    donationInfo: null,
    needs: [
      { id: "3-1", item: "Kits de primeros auxilios", priority: "alta" },
      { id: "3-2", item: "Leche en polvo", priority: "alta" },
      { id: "3-3", item: "Toallas sanitarias", priority: "media" },
    ],
    updatedLabel: "hace 3 min",
  },
  {
    id: "4",
    name: "Salón Comunitario Barrio Colombia",
    address: "90-05 Roosevelt Ave, Queens, NY",
    city: "NYC",
    status: "cerrado",
    mapsUrl: "https://maps.google.com/?q=90-05+Roosevelt+Ave+Queens+NY",
    donationInfo: null,
    needs: [],
    updatedLabel: "hace 2 h",
  },
  {
    id: "5",
    name: "Iglesia Adventista Hispana",
    address: "77 Franklin St, Bloomfield, NJ",
    city: "NJ",
    status: "abierto",
    mapsUrl: "https://maps.google.com/?q=77+Franklin+St+Bloomfield+NJ",
    donationInfo: null,
    needs: [
      { id: "5-1", item: "Carpas y sleeping bags", priority: "media" },
      { id: "5-2", item: "Guantes de trabajo", priority: "baja" },
    ],
    updatedLabel: "hace 25 min",
  },
];
